### ISSUE TITLE
Canton data for week 24

### ISSUE THREAD

**Issue by jb3-2** [maekke/bag_data#1]
Hi, thanks for your great work! 

I have browsed through the files in https://www.bag.admin.ch/dam/bag/de/dokumente/mt/k-und-i/aktuelle-ausbrueche-pandemien/2019-nCoV/bisherige-lageberichte-zip.zip.download.zip/Epidemiologische_Lage_Schweiz.zip and have found data for week 24 that you have not been added to your canton csv files yet, see Web_200625_KW25_Internettext Woche Lage Inland_DE.pdf

 ...just in case you would like to manually enhance the data. 

![image](https://user-images.githubusercontent.com/7261044/88668446-f03df500-d0e2-11ea-8eb5-a566f1d67b68.png)

**Comment by maekke** [comment]
Great, thank you for your feedback and that this data has been used... :+1: 
I've improved the cleanup script a bit a8e8868fd354ccd918ca891854cf80412d9b2abe and this is the resulting data 5a0c60b274246f56cb687c3d9aded854add4fe6a.
I totally forgot about this, but I hope it's more or less properly addressed now.
